Repository typi-team/ultra-ios, pull requests merged in 2024-02, with the labels that each got.

#99 Feature/preview of video
  UltraCore/Classes/Sources/DAO/Repositories/MediaRepository.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/IncomingPhotoCell.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/MediaCell.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/OutgoingPhotoCell.swift
Labels: future, need review

#113 При отправке денег анимация странная
  UltraCore/Classes/Sources/Modules/Conversation/Components/AdditioanalController.swift
  UltraCore/Classes/Sources/Modules/MoneyTransfer/MoneyTransferViewController.swift
Labels: bug

#114 Bugfix/audio not work from android
  UltraCore/Classes/Sources/Utils/MediaUtils.swift
Labels: need review

#115 Bugfix/audio duration
  UltraCore/Classes/Sources/DAO/Repositories/VoiceRepository.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/IncomeVoiceCell.swift
  UltraCore/Classes/Sources/Utils/Extensions/NSObject+Ext.swift
Labels: need review

#116 Bugfix/lost grpc connection
  Example/Podfile.lock
  Example/UltraCore.xcworkspace/xcuserdata/yerkebulanamankul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UltraCore/Classes/Sources/Utils/AppSettingsImpl.swift
Labels: need review
