Repository typi-team/ultra-ios, pull requests merged in 2024-01, with the labels that each got.

#56 Bugfix/memory leak
  UltraCore/Classes/Sources/Modules/Conversation/Components/MessageInputBar.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/VoiceRecord/BucketImageView.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/VoiceRecord/RecordView.swift
  UltraCore/Classes/Sources/Modules/Conversation/ConversationPresenter.swift
Labels: bug, need review

#57 Bugfix for audio recipient
  UltraCore/Classes/Sources/DAO/Store/MessageDBService.swift
  UltraCore/Classes/Sources/Modules/Conversation/ConversationPresenter.swift
  UltraCore/Classes/Sources/Modules/Conversation/Interactors/CreateFileInteractor.swift
  UltraCore/Classes/Sources/Modules/Conversation/Interactors/SendMessageInteractor.swift
  UltraCore/Classes/Sources/Modules/Conversation/Interactors/UploadFileInteractor.swift
  UltraCore/Classes/Sources/Utils/MediaUtils.swift
Labels: bug, done

#60 Добавил метод для получения статуса контактов после первой регистраций
  Example/UltraCore/Pages/ViewController.swift
  Example/UltraCore/Pages/ViewModel.swift
  UltraCore/Classes/Sources/DAO/Repositories/UpdateRepository.swift
  UltraCore/Classes/Sources/Modules/SignUp/FFSignUpPresenter.swift
Labels: bug, need review

#61 Bugfix/audio buble sliding
  UltraCore/Classes/Sources/DAO/Repositories/VoiceRepository.swift
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/IncomeVoiceCell.swift
  UltraCore/Classes/Sources/Utils/Extensions/Int64+Extensions.swift
  UltraCore/Classes/Sources/Utils/Extensions/NSObject+Ext.swift
Labels: bug, need review

#62 Добавил получение статуса после запроса на ContactByUserIdInteractor.…
  UltraCore/Classes/Sources/Modules/Contacts/Interactors/ContactByUserIdInteractor.swift
Labels: future, need review

#63 Добавил отступ для ввода комента для репорта
  UltraCore/Classes/Sources/Utils/UIKit+Extensions/TextFields.swift
Labels: bug, need review

#65 Добавил отступ после редактирования
  Example/UltraCore/en.lproj/Localizable.strings
  Example/UltraCore/ru.lproj/Localizable.strings
  UltraCore/Classes/Sources/Modules/Conversation/Components/ReportCommentController.swift
  UltraCore/Classes/Sources/Modules/Conversation/Interactors/MakeSoundInteractor.swift
  UltraCore/Classes/Sources/Utils/UIKit+Extensions/TextFields.swift
Labels: bug, need review

#66 Bugfix/decrease counter not read messages
  UltraCore/Classes/Sources/DAO/Store/MessageDBService.swift
Labels: bug, need review

#70 Bugfix/play sound in silent mode
  UltraCore/Classes/Sources/Modules/Conversation/Interactors/MakeSoundInteractor.swift
Labels: bug, need review

#77 Убрать Keyboard accessory и сделать скрытие клавиатуры по скроллу вниз
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/BaseMessageCell.swift
  UltraCore/Classes/Sources/Modules/Conversation/ConversationViewController.swift
Labels: future, need review

#81 fix bubble selection and duration
  UltraCore/Classes/Sources/Modules/Conversation/Components/Cells/BaseMessageCell.swift
  UltraCore/Classes/Sources/Modules/Conversation/ConversationViewController.swift
Labels: need review
